nmae: Deploy EC2
on:
  push:
    branch:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh ec2로그인
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }} # EC2의 주소
          username: ${{ secrets.USERNAME }} # EC2 접속 username
          key: ${{ secrets.PASSWORD }}
~                                        