name: Deploy EC2
on:
  push:
    branch:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh ec2로그인
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }} # EC2의 주소
          username: ${{ secrets.USERNAME }} # EC2 접속 username
          key: ${{ secrets.PASSWORD }}
          script: |
            cd /home/codelabSpring
            git config --global --add safe.directory /home/codelabSpring/12_jpa_crud
            sudo git pull origin main
            sudo ./gradlew clean build
            sudo fuser -k -n tcp 8080 
            # nohup java -jar build/libs/*SNAPSHOT.war & cd
            nohup java -jar build/libs/*SNAPSHOT.war > /dev/null 2>&1 &
            sudo lsof -i:8080                                    
